version: "3.3"
services:
  backend:
    image: saiga-gpu:latest
    container_name: backend
    build:
      context: backend/saiga
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
      - "8082:8082"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 0
              capabilities: [gpu]
